# Official CMS RVU25B Data - 2025 Physician Fee Schedule
# Source: https://www.cms.gov/medicare/payment/fee-schedules/physician/pfs-relative-value-files/rvu25b
# All wRVU values verified against official CMS RVU25B data file

WRVU_DATA = {
    "CT Head without contrast": {"cpt": "70450", "wrvu": 0.85, "description": "CT head/brain without contrast"},
    "CT Head with contrast": {"cpt": "70460", "wrvu": 1.13, "description": "CT head/brain with contrast"},
    "CT Head without and with contrast": {"cpt": "70470", "wrvu": 1.27, "description": "CT head/brain without and with contrast"},
    "CT Orbit/Sella without contrast": {"cpt": "70480", "wrvu": 1.28, "description": "Ct orbit/ear/fossa w/o dye"},
    "CT Orbit/Sella with contrast": {"cpt": "70481", "wrvu": 1.13, "description": "Ct orbit/ear/fossa w/dye"},
    "CT Orbit/Sella without and with contrast": {"cpt": "70482", "wrvu": 1.27, "description": "Ct orbit/ear/fossa w/o&w/dye"},
    "CT Soft Tissue Neck without contrast": {"cpt": "70490", "wrvu": 1.28, "description": "Ct soft tissue neck w/o dye"},
    "CT Soft Tissue Neck with contrast": {"cpt": "70491", "wrvu": 1.38, "description": "Ct soft tissue neck w/dye"},
    "CT Soft Tissue Neck without and with contrast": {"cpt": "70492", "wrvu": 1.62, "description": "Ct sft tsue nck w/o & w/dye"},
    "CT Chest without contrast": {"cpt": "71250", "wrvu": 1.08, "description": "Ct thorax dx c-"},
    "CT Chest with contrast": {"cpt": "71260", "wrvu": 1.16, "description": "Ct thorax dx c+"},
    "CT Chest without and with contrast": {"cpt": "71270", "wrvu": 1.25, "description": "Ct thorax dx c-/c+"},
    "CT Abdomen without contrast": {"cpt": "74150", "wrvu": 1.19, "description": "Ct abdomen w/o contrast"},
    "CT Abdomen with contrast": {"cpt": "74160", "wrvu": 1.27, "description": "Ct abdomen w/contrast"},
    "CT Abdomen without and with contrast": {"cpt": "74170", "wrvu": 1.4, "description": "Ct abd wo cntrst flwd cntrst"},
    "CT Pelvis without contrast": {"cpt": "72192", "wrvu": 1.09, "description": "Ct pelvis w/o dye"},
    "CT Pelvis with contrast": {"cpt": "72193", "wrvu": 1.16, "description": "Ct pelvis w/dye"},
    "CT Pelvis without and with contrast": {"cpt": "72194", "wrvu": 1.22, "description": "Ct pelvis w/o & w/dye"},
    "CT Abdomen and Pelvis without contrast": {"cpt": "74176", "wrvu": 1.74, "description": "Ct abd & pelvis w/o contrast"},
    "CT Abdomen and Pelvis with contrast": {"cpt": "74177", "wrvu": 1.82, "description": "CT abdomen and pelvis with contrast"},
    "CT Abdomen and Pelvis without and with contrast": {"cpt": "74178", "wrvu": 2.01, "description": "Ct abd&plv wo cntr flwd cntr"},
    "CT Chest/Abdomen/Pelvis without contrast": {"cpt": "74181", "wrvu": 1.46, "description": "Mri abdomen w/o contrast"},
    "CT Chest/Abdomen/Pelvis with contrast": {"cpt": "74182", "wrvu": 1.73, "description": "Mri abdomen w/contrast"},
    "CT Chest/Abdomen/Pelvis without and with contrast": {"cpt": "74183", "wrvu": 2.2, "description": "Mri abd w/o cntr flwd cntr"},
    "CT Angiography Head": {"cpt": "70496", "wrvu": 1.75, "description": "Ct angiography head"},
    "CT Angiography Neck": {"cpt": "70498", "wrvu": 1.75, "description": "Ct angiography neck"},
    "CT Angiography Chest": {"cpt": "71275", "wrvu": 1.82, "description": "Ct angiography chest"},
    "CT Angiography Abdomen": {"cpt": "74175", "wrvu": 1.82, "description": "Cta abdomen w/contrast"},
    "CT Angiography Pelvis": {"cpt": "72191", "wrvu": 1.81, "description": "Ct angiograph pelv w/o&w/dye"},
    "CT Angiography Lower Extremity": {"cpt": "73706", "wrvu": 1.9, "description": "Ct angio lwr extr w/o&w/dye"},
    "CT Angiography Upper Extremity": {"cpt": "73206", "wrvu": 1.81, "description": "Ct angio upr extrm w/o&w/dye"},
    "MRI Brain without contrast": {"cpt": "70551", "wrvu": 1.48, "description": "MRI brain stem without contrast"},
    "MRI Brain with contrast": {"cpt": "70552", "wrvu": 1.78, "description": "MRI brain stem with contrast"},
    "MRI Brain without and with contrast": {"cpt": "70553", "wrvu": 2.29, "description": "MRI brain stem without and with contrast"},
    "MRI Orbit/Face/Neck without contrast": {"cpt": "70540", "wrvu": 1.35, "description": "Mri orbit/face/neck w/o dye"},
    "MRI Orbit/Face/Neck with contrast": {"cpt": "70542", "wrvu": 1.62, "description": "Mri orbit/face/neck w/dye"},
    "MRI Orbit/Face/Neck without and with contrast": {"cpt": "70543", "wrvu": 2.15, "description": "Mri orbt/fac/nck w/o &w/dye"},
    "MRI Cervical Spine without contrast": {"cpt": "72141", "wrvu": 1.48, "description": "Mri neck spine w/o dye"},
    "MRI Cervical Spine with contrast": {"cpt": "72142", "wrvu": 1.78, "description": "Mri neck spine w/dye"},
    "MRI Cervical Spine without and with contrast": {"cpt": "72146", "wrvu": 1.48, "description": "Mri chest spine w/o dye"},
    "MRI Thoracic Spine without contrast": {"cpt": "72146", "wrvu": 1.48, "description": "Mri chest spine w/o dye"},
    "MRI Thoracic Spine with contrast": {"cpt": "72147", "wrvu": 1.78, "description": "Mri chest spine w/dye"},
    "MRI Thoracic Spine without and with contrast": {"cpt": "72148", "wrvu": 1.48, "description": "Mri lumbar spine w/o dye"},
    "MRI Lumbar Spine without contrast": {"cpt": "72148", "wrvu": 1.48, "description": "Mri lumbar spine w/o dye"},
    "MRI Lumbar Spine with contrast": {"cpt": "72149", "wrvu": 1.78, "description": "Mri lumbar spine w/dye"},
    "MRI Lumbar Spine without and with contrast": {"cpt": "72158", "wrvu": 2.29, "description": "Mri lumbar spine w/o & w/dye"},
    "MRI Abdomen without contrast": {"cpt": "74181", "wrvu": 1.46, "description": "Mri abdomen w/o contrast"},
    "MRI Abdomen with contrast": {"cpt": "74182", "wrvu": 1.73, "description": "Mri abdomen w/contrast"},
    "MRI Abdomen without and with contrast": {"cpt": "74183", "wrvu": 2.2, "description": "Mri abd w/o cntr flwd cntr"},
    "MRI Pelvis without contrast": {"cpt": "72195", "wrvu": 1.46, "description": "Mri pelvis w/o dye"},
    "MRI Pelvis with contrast": {"cpt": "72196", "wrvu": 1.73, "description": "Mri pelvis w/dye"},
    "MRI Pelvis without and with contrast": {"cpt": "72197", "wrvu": 2.2, "description": "Mri pelvis w/o & w/dye"},
    "MRI Chest without contrast": {"cpt": "71550", "wrvu": 1.46, "description": "Mri chest w/o dye"},
    "MRI Chest with contrast": {"cpt": "71551", "wrvu": 1.73, "description": "Mri chest w/dye"},
    "MRI Chest without and with contrast": {"cpt": "71552", "wrvu": 2.26, "description": "Mri chest w/o & w/dye"},
    "MRI Upper Extremity without contrast": {"cpt": "73218", "wrvu": 1.35, "description": "Mri upper extremity w/o dye"},
    "MRI Upper Extremity with contrast": {"cpt": "73219", "wrvu": 1.62, "description": "Mri upper extremity w/dye"},
    "MRI Upper Extremity without and with contrast": {"cpt": "73220", "wrvu": 2.15, "description": "Mri uppr extremity w/o&w/dye"},
    "MRI Lower Extremity without contrast": {"cpt": "73718", "wrvu": 1.35, "description": "Mri lower extremity w/o dye"},
    "MRI Lower Extremity with contrast": {"cpt": "73719", "wrvu": 1.62, "description": "Mri lower extremity w/dye"},
    "MRI Lower Extremity without and with contrast": {"cpt": "73720", "wrvu": 2.15, "description": "Mri lwr extremity w/o&w/dye"},
    "Ultrasound Abdomen Complete": {"cpt": "76700", "wrvu": 0.81, "description": "Us exam abdom complete"},
    "Ultrasound Abdomen Limited": {"cpt": "76705", "wrvu": 0.59, "description": "Echo exam of abdomen"},
    "Ultrasound Pelvis Complete": {"cpt": "76856", "wrvu": 0.69, "description": "Us exam pelvic complete"},
    "Ultrasound Pelvis Limited": {"cpt": "76857", "wrvu": 0.5, "description": "Us exam pelvic limited"},
    "Ultrasound Thyroid": {"cpt": "76536", "wrvu": 0.56, "description": "Us exam of head and neck"},
    "Ultrasound Carotid": {"cpt": "93880", "wrvu": 0.8, "description": "Extracranial bilat study"},
    "Ultrasound Renal": {"cpt": "76770", "wrvu": 0.74, "description": "Us exam abdo back wall comp"},
    "Ultrasound Scrotum": {"cpt": "76870", "wrvu": 0.64, "description": "Us exam scrotum"},
    "Ultrasound Breast": {"cpt": "76641", "wrvu": 0.73, "description": "Ultrasound breast complete"},
    "Ultrasound Obstetric": {"cpt": "76801", "wrvu": 0.99, "description": "Ob us < 14 wks single fetus"},
    "Ultrasound Fetal Biometry": {"cpt": "76805", "wrvu": 0.99, "description": "Ob us >= 14 wks sngl fetus"},
    "Ultrasound Fetal Detailed": {"cpt": "76811", "wrvu": 1.9, "description": "Ob us detailed sngl fetus"},
    "Mammography Screening Bilateral": {"cpt": "77067", "wrvu": 0.76, "description": "Screening mammography bilateral including CAD"},
    "Mammography Diagnostic Unilateral": {"cpt": "77065", "wrvu": 0.81, "description": "Dx mammo incl cad uni"},
    "Mammography Diagnostic Bilateral": {"cpt": "77066", "wrvu": 1.0, "description": "Dx mammo incl cad bi"},
    "Mammography Tomosynthesis Screening": {"cpt": "77067", "wrvu": 0.76, "description": "Screening mammography bilateral including CAD"},
    "Spine X-ray Cervical 2 Views": {"cpt": "72020", "wrvu": 0.16, "description": "X-ray exam of spine 1 view"},
    "Spine X-ray Thoracic 2 Views": {"cpt": "72070", "wrvu": 0.2, "description": "X-ray exam thorac spine 2vws"},
    "Spine X-ray Thoracic 3 Views": {"cpt": "72072", "wrvu": 0.23, "description": "X-ray exam thorac spine 3vws"},
    "Spine X-ray Lumbar 2 Views": {"cpt": "72100", "wrvu": 0.22, "description": "X-ray exam l-s spine 2/3 vws"},
    "Spine X-ray Lumbar 3 Views": {"cpt": "72110", "wrvu": 0.26, "description": "X-ray exam l-2 spine 4/>vws"},
    "Spine X-ray Lumbar 4 Views": {"cpt": "72114", "wrvu": 0.3, "description": "X-ray exam l-s spine bending"},
    "Extremity X-ray Upper": {"cpt": "73060", "wrvu": 0.16, "description": "X-ray exam of humerus"},
    "Extremity X-ray Lower": {"cpt": "73610", "wrvu": 0.17, "description": "X-ray exam of ankle"},
    "Bone Scan Whole Body": {"cpt": "78315", "wrvu": 1.02, "description": "Bone imaging 3 phase"},
    "Thyroid Scan": {"cpt": "78012", "wrvu": 0.19, "description": "Thyroid uptake measurement"},
    "Thyroid Uptake": {"cpt": "78013", "wrvu": 0.37, "description": "Thyroid imaging w/blood flow"},
    "Cardiac Stress Test": {"cpt": "78452", "wrvu": 1.62, "description": "Ht muscle image spect mult"},
    "Cardiac Rest Test": {"cpt": "78451", "wrvu": 1.38, "description": "Ht muscle image spect sing"},
    "Renal Scan": {"cpt": "78700", "wrvu": 0.45, "description": "Kidney imaging morphol"},
    "Angiography Cerebral": {"cpt": "36221", "wrvu": 3.92, "description": "Place cath thoracic aorta"},
    "Angiography Carotid": {"cpt": "36222", "wrvu": 5.28, "description": "Place cath carotid/inom art"},
    "Angiography Renal": {"cpt": "36245", "wrvu": 4.65, "description": "Ins cath abd/l-ext art 1st"},
    "Angiography Mesenteric": {"cpt": "36246", "wrvu": 5.02, "description": "Ins cath abd/l-ext art 2nd"},
    "Angiography Lower Extremity": {"cpt": "36247", "wrvu": 6.04, "description": "Ins cath abd/l-ext art 3rd"},
    "Angiography Upper Extremity": {"cpt": "36215", "wrvu": 4.17, "description": "Place catheter in artery"},
    "Percutaneous Drainage": {"cpt": "49405", "wrvu": 4.0, "description": "Image cath fluid colxn visc"},
    "Biopsy CT Guided": {"cpt": "77012", "wrvu": 1.5, "description": "Ct scan for needle biopsy"},
    "Biopsy Ultrasound Guided": {"cpt": "76942", "wrvu": 0.67, "description": "Echo guide for biopsy"},
    "Biopsy MRI Guided": {"cpt": "77021", "wrvu": 1.5, "description": "Mri guidance ndl plmt rs&i"},
    "DEXA Scan": {"cpt": "77080", "wrvu": 0.2, "description": "DEXA bone density axial"},
    "DEXA Scan Peripheral": {"cpt": "77081", "wrvu": 0.2, "description": "Dxa bone density appendiculr"},
    "Fluoroscopy Upper GI": {"cpt": "74246", "wrvu": 0.9, "description": "X-ray xm upr gi trc 2cntrst"},
    "Fluoroscopy Lower GI": {"cpt": "74270", "wrvu": 1.04, "description": "X-ray xm colon 1cntrst std"},
    "Fluoroscopy Esophagram": {"cpt": "74220", "wrvu": 0.6, "description": "X-ray xm esophagus 1cntrst"},
    "Fluoroscopy Swallow Study": {"cpt": "74230", "wrvu": 0.53, "description": "X-ray xm swlng funcj c+"},
    "Prostate MRI": {"cpt": "72197", "wrvu": 2.2, "description": "Mri pelvis w/o & w/dye"},
    "Prostate MRI with Contrast": {"cpt": "72198", "wrvu": 1.8, "description": "Mr angio pelvis w/o & w/dye"},
    "Musculoskeletal MRI": {"cpt": "73718", "wrvu": 1.35, "description": "Mri lower extremity w/o dye"},
    "Pediatric Imaging": {"cpt": "70450", "wrvu": 0.85, "description": "CT head/brain without contrast"},
    "Emergency Radiology": {"cpt": "70450", "wrvu": 0.85, "description": "CT head/brain without contrast"},
    "Neuroradiology": {"cpt": "70551", "wrvu": 1.48, "description": "MRI brain stem without contrast"},
    "Body Imaging": {"cpt": "74150", "wrvu": 1.19, "description": "Ct abdomen w/o contrast"},
    "Women's Imaging": {"cpt": "77067", "wrvu": 0.76, "description": "Screening mammography bilateral including CAD"},
}
